name: Echo Workflow

on:
  push:
    branches:
      - main

jobs:
  echo-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display Name
      run: echo "Hello, I am ChatGPT!"
