name: Run Jest Tests and Artifact

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Navigate to Project Directory
        run: |
          cd lab1
          npm install
          npm test

      - name: Building the project for Artifact
        run: |
          cd lab1
          npm install
          npm run build

      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: lab1-artifact
          path: lab1/dist

      - name: API key setup
        run: echo ${{ secrets.API_KEY }}
